name: MANUAL MODE - IOT MAINTENANCE

on:
  workflow_dispatch:


jobs:
  telegram_job:
    runs-on: ubuntu-latest
    steps:    
   
    - name: Checkout Repo Content
      uses: actions/checkout@v2
 
    - name: Run
      env:
        MY_SITE: ${{secrets.MY_SITE}}
      run: |
        curl -Z -vv "https://$MY_SITE/?stobsoft=[1-2000]"
